server:
  port: 48006

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #8.X数据库驱动文件
    #    driver-class-name: com.mysql.jdbc.Driver #5.X数据库驱动文件
    url: jdbc:mysql://8.130.40.72:3306/btp_training
    username: btp
    password: 123456
  redis:
    host: 8.130.40.72
    port: 6379
    password: btptraining
    database: 5
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
  cache:
    type: redis
    cache-names: material


mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true #避免实体类属性驼峰格式与数据库不一致

#showSql
logging:
  level:
    root: info
    com.btp.rwj: debug

salt: 891840248jhjkh